version: "3.8"

services:
  opentelastic:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure the Dockerfile is in the correct location or specify the path
    ports:
      - "9097:9097"
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://otel-collector:4317" ]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

    depends_on:
      - elasticsearch
    networks:
      - otel-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s
    networks:
      - otel-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.5
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
