receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]  # Elasticsearch container hostname and port
    logs_index: "otel-logs"  # New option for logs
    traces_index: "otel-traces"  # New option for traces


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
